version: '3'

services:
  api:
    image: 127.0.0.1:5000/api
    build: ./api
    volumes:
      - shared:/usr/src/app/shared
    ports:
      - "8080:8080"
  provisioning:
    image: 127.0.0.1:5000/provisioning
    build: ./provisioning
    volumes:
      - shared:/code/shared
    ports:
      - "8000:8000"
  scanning:
    image: 127.0.0.1:5000/scanning
    build: ./scanning
    volumes:
      - shared:/usr/src/app/shared
volumes:
  shared: 